### ISSUE TITLE
Conversation isn't marked as read if you have another app for sms.

### ISSUE THREAD

**Issue by oscarmcm** [qklabs/qksms-tracker#51]
### DESCRIPTION
Conversations aren't marked as read when you have another sms app for default.

### STEPS
1. Set another sms app for default in your phone.
2. Use the app that you have selected for default.
3. Open QKSMS and open one conversation with one new message.

### EXPECTED
The conversation is marked as read.

### REALITY
The conversation isn't marked as read.

**Comment by srcreigh** [comment]
Thanks for the awesome report @oscarmcm! Turns out we actually can't mark things as read when we're not the default SMS app.. We should definitely put in some kind of indicator for that though, i.e. "Make default SMS to mark as read" or something.

I'm going to leave this as a bug because it comes across as one to users.

**Comment by oscarmcm** [comment]
Yes, it is more a problem of usability. Maybe you can add a message or another thing, that notify to the user that QKSMS is not the default sms app and add the ability to set this for default.

**Comment by moezbhatti** [comment]
Agreed, we should definitely be more clear about the process of setting the app to default and what that actually does

**Comment by srcreigh** [comment]
Closing because we have UI for this
